version: '3.4'

services:
  sentiment_analysis_api:
    image: sentiment_analysis_api
    environment:
      - train_model=true 
    ports:
      - "5000:5000"
    volumes:
      - /home/sentiment-model/models:/sentiment-clf/lib/models

